<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>inspection_bringup</name>
  <version>0.1.0</version>
  <description>Launch files and parameter assembly for the quadruped inspection robot.</description>
  <maintainer email="xyt1351325@hotmail.com">青岛港湾职业技术学院 灵枢智行团队</maintainer>
  <author>青岛港湾职业技术学院 灵枢智行团队 (qdgw / lszx_byc)</author>
  <license>proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>inspection_execution_cpp</exec_depend>
  <exec_depend>inspection_planning_py</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
