"""解释 C++ 端返回的统一错误码。"""

OK = 0
INVALID_GOAL = 1001
GOAL_EXPIRED = 1002
STALE_SENSOR_DATA = 2001
SENSOR_INVALID = 2002
SAFETY_REJECTED = 3001
EXECUTION_FAILED = 4001
CORRIDOR_INVALID = 5001
LOCALIZATION_DEGRADED = 6001
THERMAL_OUT_OF_RANGE = 7001
ACOUSTIC_LOW_CONFIDENCE = 8001

_DESCRIPTIONS = {
    OK: "OK",
    INVALID_GOAL: "INVALID_GOAL",
    GOAL_EXPIRED: "GOAL_EXPIRED",
    STALE_SENSOR_DATA: "STALE_SENSOR_DATA",
    SENSOR_INVALID: "SENSOR_INVALID",
    SAFETY_REJECTED: "SAFETY_REJECTED",
    EXECUTION_FAILED: "EXECUTION_FAILED",
    CORRIDOR_INVALID: "CORRIDOR_INVALID",
    LOCALIZATION_DEGRADED: "LOCALIZATION_DEGRADED",
    THERMAL_OUT_OF_RANGE: "THERMAL_OUT_OF_RANGE",
    ACOUSTIC_LOW_CONFIDENCE: "ACOUSTIC_LOW_CONFIDENCE",
}


def describe(code: int) -> str:
    return _DESCRIPTIONS.get(code, "UNKNOWN")
