"""与 C++ 端保持一致的 Topic 命名表。"""

ROBOT_STATE = "/robot_state"
OPERATOR_INSTRUCTION = "/operator_instruction"
INSPECTION_ALERT = "/inspection_alert"
STRUCTURED_GOAL = "/structured_goal"
TASK = "/task"
ENERGY_CONSTRAINT = "/energy_constraint"
TASK_DECISION = "/task_decision"
TERRAIN_OBSERVATION = "/terrain_observation"
CORRIDOR_STATE = "/corridor_state"
GRATING_STATUS = "/grating_status"
FUSION_POSE = "/fusion_pose"
SEMANTIC_ALARM = "/semantic_alarm"
THERMAL_MEASUREMENT = "/thermal_measurement"
ACOUSTIC_DIAGNOSIS = "/acoustic_diagnosis"
ACOUSTIC_MONO = "/acoustic_mono"

IMU = "/imu"
FOOT_FORCE = "/foot_force"
LIDAR_SCAN = "/lidar_scan"
IMAGE = "/image"
THERMAL_IMAGE = "/thermal_image"
AUDIO_MULTI_CHANNEL = "/audio_multi_channel"

# Service / Action 名称
VALIDATE_GOAL_SERVICE = "/validate_goal"
RESUME_TASK_SERVICE = "/resume_task"
EXECUTE_TASK_ACTION = "/execute_task"
NAVIGATE_GOAL_ACTION = "/navigate_goal"
